grupo: 1
lenguaje: L1_aho
integrantes:
  - Martucci, Federico Ariel
  - Branchesi, Tomas Agustin
  - Brocani, Agustin
  - Bianchi, Juan Alberto
  - Lopez Rodofile, Alejo
temas_especiales:
  - TE1_matchPatterns
  - TE3_powerSpaceship
notacion: polaca_inversa
profesor: Daniel
