grupo: 1
lenguaje: L1_aho
integrantes:
  - Martucci_Federico
  - Branchesi_Tomas
  - Brocani_Agustin
  - Bianchi_Juan
  - Lopez_Rodofile_Alejo 
temas_especiales:
  - TE1_matchPatterns
  - TE3_powerSpaceship
notacion: polaca_inversa
profesor: Daniel
